### ISSUE TITLE
请问一下如何扫描蓝牙连接

### ISSUE THREAD

**Issue by nletech** [thon-ju/bluetooth_print#1]
请问一下如何扫描蓝牙连接
谢谢

**Comment by thon-ju** [comment]
@nletech 扫描蓝牙连接，你是指没有和手机配对的蓝牙吗

**Comment by nletech** [comment]
@thon-ju 我现在用的是GP1324D , 通过手机配对上了，然后使用DEMO，连接过了5秒后就自动断开了，
如果点快一点连接后点击打印，就会报：PlatformException (PlatformException(not connect, state not right, null))

**Comment by nletech** [comment]
打印自检也是一样，有特定打印机的要求吗

**Comment by thon-ju** [comment]
@nletech 是条码打印机吗？这个部分代码目前版本没有加如进去，如果特别需要的话，可以考虑最近加进去

**Comment by nletech** [comment]
是面单打印机，可以打面单和条码

**Comment by nletech** [comment]
@thon-ju 
这个是他们官方的SDK
链接: https://pan.baidu.com/s/1URFhAY4E3Uxb6-wY88Qo0A 提取码: 45yt 

你要是有空的话可以关注一下，谢谢

**Comment by thon-ju** [comment]
@nletech 好的，这周会添加支持

**Comment by thon-ju** [comment]
@nletech 增加了对面单和标签模式的支持，你可以试试最新版，打印自检是否正常。自定义打印周末发布一个版本

**Comment by nletech** [comment]
@thon-ju 感谢哈，刚刚试了一下是可以打印了，
不过打印机并不知道是什么打印纸张，所以打印这块，是否能支持设置一下打印的模板尺寸，谢谢

**Comment by thon-ju** [comment]
@nletech 已完成标签模式打印，参考示例example/lib/main.dart中 print label
