### ISSUE TITLE
Cut the top padding

### ISSUE THREAD

**Issue by MrSobirov** [thon-ju/bluetooth_print#106]
How can I cut the extra padding on the top of the receipt? I'm getting extra 50 px at the top. Any solution?

**Comment by MrSobirov** [comment]
I have been trying to print in esc mode, use tspl or cpcl modes instead to print labels and tickets, not receipts

**Comment by hkeyz** [comment]
> I have been trying to print in esc mode, use tspl or cpcl modes instead to print labels and tickets, not receipts

How to change the mode?

**Comment by MrSobirov** [comment]
Read the instructions book of printer, on the menu you can find it
