### ISSUE TITLE
Unable to create release APK

### ISSUE THREAD

**Issue by kevinconcourse** [thon-ju/bluetooth_print#116]
command: flutter build apk --split-per-abi
Error Stack:

w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/test/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.30/5fd47535cc85f9e24996f939c2de6583991481b0/kotlin-stdlib-jdk8-1.5.30.jar (version 1.5)
    /Users/test/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)
    /Users/test/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.10/b8af3fe6f1ca88526914929add63cf5e7c5049af/kotlin-stdlib-1.6.10.jar (version 1.6)
    /Users/test/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.10/c118700e3a33c8a0d9adc920e9dec0831171925/kotlin-stdlib-common-1.6.10.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
ERROR:/Users/test/Documents/flutter_sample/bluetooth_print/build/bluetooth_print/intermediates/runtime_library_classes_jar/release/classes.jar: R8: Type com.example.bluetooth_print.BuildConfig is defined multiple times: /Users/test/Documents/flutter_sample/bluetooth_print/build/bluetooth_print/intermediates/runtime_library_classes_jar/release/classes.jar:com/example/bluetooth_print/BuildConfig.class, /Users/test/Documents/flutter_sample/bluetooth_print/build/app/intermediates/javac/release/classes/com/example/bluetooth_print/BuildConfig.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/test/Documents/flutter_sample/bluetooth_print/build/bluetooth_print/intermediates/runtime_library_classes_jar/release/classes.jar:com/example/bluetooth_print/BuildConfig.class

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

**Comment by YouSour** [comment]
i got the same problem 😞

**Comment by kevinconcourse** [comment]
> 

Did you try latest version of this plugin?

**Comment by YouSour** [comment]
@kevinconcourse yes, i just test it a few min ago , it works.

**Comment by kevinconcourse** [comment]
user@test-MacBook-Pro bluetooth_print % flutter build apk --split-per-abi --no-shrink

💪 Building with sound null safety 💪

ERROR:/Users/user/Documents/flutter_sample/bluetooth_print/build/bluetooth_print/intermediates/runtime_library_classes_jar/release/classes.jar: R8: Type com.example.bluetooth_print.BuildConfig is defined multiple times: /Users/user/Documents/flutter_sample/bluetooth_print/build/bluetooth_print/intermediates/runtime_library_classes_jar/release/classes.jar:com/example/bluetooth_print/BuildConfig.class, /Users/user/Documents/flutter_sample/bluetooth_print/build/app/intermediates/javac/release/classes/com/example/bluetooth_print/BuildConfig.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/user/Documents/flutter_sample/bluetooth_print/build/bluetooth_print/intermediates/runtime_library_classes_jar/release/classes.jar:com/example/bluetooth_print/BuildConfig.class

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleRelease'...                         2,757ms

┌─ Flutter Fix ──────────────────────────────────────────────────────────────┐
│ [!] The shrinker may have failed to optimize the Java bytecode.            │
│ To disable the shrinker, pass the `--no-shrink` flag to this command.      │
│ To learn more, see: https://developer.android.com/studio/build/shrink-code │
└───────────────────────────────────────────────────────
