### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by Tanvirul-swe** [thon-ju/bluetooth_print#118]
A problem occurred evaluating project ':bluetooth_print'.
> Could not find method compile() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by shubhjagani** [comment]
also seeing this @thon-ju any update?

**Comment by shubhjagani** [comment]
@Tanvirul-swe I found the fix. 
start by running  `flutter clean`

go to the build.gradle for this package for me the path was 
```/Users/shubh/dev/flutter/.pub-cache/hosted/pub.dartlang.org/bluetooth_print-3.0.0/android/build.gradle``` 
and replace line 37 where it say says `compile files ...` with `implementation files...`
