### ISSUE TITLE
Andorid connected to the printer and filled in the correct pin code 0000, but it was prompted that the pin code was wrong, and then the console reported an error! Forget the answer, thank you!

### ISSUE THREAD

**Issue by Tate-zwt** [thon-ju/bluetooth_print#125]
W/System.err(22488): java.io.IOException: read failed, socket might closed or timeout, read ret: -1
W/System.err(22488): 	at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:686)
W/System.err(22488): 	at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:645)
W/System.err(22488): 	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:379)
W/System.err(22488): 	at com.gprinter.io.BluetoothPort.openPort(BluetoothPort.java:58)
W/System.err(22488): 	at com.example.bluetooth_print.DeviceConnFactoryManager.openPort(DeviceConnFactoryManager.java:150)
W/System.err(22488): 	at com.example.bluetooth_print.BluetoothPrintPlugin$3.run(BluetoothPrintPlugin.java:346)
W/System.err(22488): 	at com.example.bluetooth_print.ThreadPool$1.run(ThreadPool.java:78)
W/System.err(22488): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err(22488): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err(22488): 	at java.lang.Thread.run(Thread.java:764)

When I filled in the correct pin code during connection, it still showed that it did not match, and this error was reported later. Hope you can reply, thank you!

**Comment by Tate-zwt** [comment]
bluetooth_print 4.3.0 version

**Comment by zzy080615** [comment]
i have same problem，How did you solve it？？

**Comment by biloo-dev** [comment]
Is there any update on this issue?
I have the same problem with the pin code?? 
Please let us know if it has been resolved. Thanks!
