### ISSUE TITLE
支持的打印机类型

### ISSUE THREAD

**Issue by LuodiJackShen** [thon-ju/bluetooth_print#139]
请问仅支持佳博的热敏打印机吗？其他品牌的打印机是否支持呢？

**Comment by LianYangCn** [comment]
通过 [这里](https://github.com/thon-ju/bluetooth_print/tree/master/android/libs) 的这个JAR可以基本判断不支持其他的打印机

**Comment by LuodiJackShen** [comment]
试过了，不支持
