### ISSUE TITLE
/android/app/src/debug/AndroidManifest.xml Error:         uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library [:bluetooth_print]

### ISSUE THREAD

**Issue by zemunkh** [thon-ju/bluetooth_print#2]
**> /android/app/src/debug/AndroidManifest.xml Error:
>         uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library [:bluetooth_print]**

I stuck on this error in 2 days. I found the solution to this issue.

Open printer_app/android/build.gradle:
Change the following line as lower version.

```
android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 16  // Before it was 18
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}
```

However, I found the solution. I don't understand minSdk problem.

**Comment by thon-ju** [comment]
@zemunkh thank you for you test. It's fine on my mac. Could you show me your flutter doctor?, myself is:
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Applications/Contents
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] Connected device (1 available)
`

**Comment by zemunkh** [comment]
@thon-ju Hello, My Sdk is not 28. It is 29.
`[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-MN)`
```
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/zemunkh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.
```

**Comment by thon-ju** [comment]
@zemunkh ok, let me try

**Comment by thon-ju** [comment]
@zemunkh  you are right, 'minSdkVersion 16' is ok.i have fixed.Thanks

**Comment by thon-ju** [comment]
@zemunkh although 'minSdkVersion 16' can work，but suggest use  'minSdkVersion 18' ,because  the 
method ’BluetoothDevice.getType‘
