### ISSUE TITLE
ios直接闪退，无法运行

### ISSUE THREAD

**Issue by atishoo** [thon-ju/bluetooth_print#22]
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (2 weeks ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

**Comment by luyunyu** [comment]
同样碰到ios闪退问题，请问你是怎么解决的
