### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by Gioelio** [thon-ju/bluetooth_print#24]
Hi, I've tried a lot of command to increase text, including weight and size when I create LineText, I don't know if there are other commands to increase this, but I don't found it and if you can include this possibility in your code would be great. (I test only in esc mode)

**Comment by ReniDelonzek** [comment]
I have the same problem

**Comment by c0c4i** [comment]
I have same problem too, any solution?

**Comment by luoxufeiyan** [comment]
I have the same issue as well and I think this might be a solution: 

for the `esc` method, the `width` and `height` parameter also need to change when adjusting `size` to change the font size. This works for me:

```dart
list.add(LineText(
                                    type: LineText.TYPE_TEXT,
                                    content: 'BIGGGG text',
                                    size: 10,
                                    width: 10,
                                    height: 10,
                                    linefeed: 1));
```

Print result:

![image](https://user-images.githubusercontent.com/6621172/108945155-33c80400-76b0-11eb-8ae0-19cbf174e793.png)
