### ISSUE TITLE
打印BARCODE类型设置content内容失效 一直打印SMARNET

### ISSUE THREAD

**Issue by junkai-li** [thon-ju/bluetooth_print#27]
我查看你的源代码发现 这行代码if("barcode".equals(type)){
                        tsc.add1DBarcode(x, y, LabelCommand.BARCODETYPE.CODE128, 100, LabelCommand.READABEL.EANBEL, LabelCommand.ROTATION.ROTATION_0,"SMARNET");
                  }
 SMARNET已被写死 我该如何给BARCODE类型设置内容呢？

**Comment by thon-ju** [comment]
已处理，更新最新版本
