### ISSUE TITLE
功能建议：画线画框的方法

### ISSUE THREAD

**Issue by nletech** [thon-ju/bluetooth_print#3]
最近一直在关注这个项目，我也尝试用了一下，以后几点建议

1. 缺少画线的方法
2. 缺少画框的方法
3. 最好能直接发送打印指令

谢谢

**Comment by thon-ju** [comment]
@nletech 谢谢你的关注，由于安卓和ios的sdk差异较大，目前不考虑增加过滤复杂的api；
对于复杂的布局及图形，建议使用打印图片的方式，思路如下：
1、在打印预览界面进行复杂布局
2、使用https://pub.flutter-io.cn/packages/screenshot组件生成截图
3、使用打印托盘方式
示例参考
`
File image = await screenshotController.capture(pixelRatio: 5);
List<int> imageBytes = await image.readAsBytes();
String base64Image = base64Encode(imageBytes);

List<LineText> list = List();
list.add(LineText(type: LineText.TYPE_IMAGE, content: base64Image, align: LineText.ALIGN_CENTER, linefeed: 1));
await bluetoothPrint.print(list);
`

**Comment by mjl0602** [comment]
作者你好，如果打印整个widget的截图，打印机反应会非常慢。目前打印70*110尺寸的标签，打印一张需要30秒才能打印出来。

根据我们目前的测试，即使是打印全空白的widget，只要尺寸是70*110，就一定需要30秒才能打印出来。

所以想问一下，是机器的问题还是代码的问题，是否有能更快打印的打印机？

打印机型号：佳博3120TU
代码如下
```dart
    list1.add(LineText(
      type: LineText.TYPE_IMAGE,
      x: 8,
      y: 6,
      width: 530,
      content: base64Image,
    ));
```

**Comment by YouSour** [comment]
i'm using [screenshot](https://pub.flutter-io.cn/packages/screenshot) with this package , everything is black 😞 ,any idea ?
![2022-10-27 10 45 20](https://user-images.githubusercontent.com/9318106/198186429-b6384f24-5373-4949-85eb-e3b9de5a88cc.jpg)
