### ISSUE TITLE
汉印便携式打印机根本不能使用

### ISSUE THREAD

**Issue by pdliuw** [thon-ju/bluetooth_print#34]
复现步骤：

* 1. 下载此GitHub项目到电脑上
* 2. 运行项目到Android手机上，使用此app连接蓝牙打印设备：“无法与‘xxx’进行配对”
* 3. 运行项目到iOS手机上，使用此app连接蓝牙打印设备，成功地连接；使用此app进行打印数据，打印出的效果不能使用：出现了火星文-->如下图所示

![499D888FEBC0A887C1D5253B17AC0138](https://user-images.githubusercontent.com/29451779/95563990-b711f180-0a50-11eb-915c-19c88145a763.png)

急急急！

**Comment by pdliuw** [comment]
测试蓝牙设备：HM-A300

**Comment by FulingFan-1** [comment]
一样，连接打印机连接不上，一直显示配对错误

**Comment by FulingFan-1** [comment]
火星文是因为你没有转成GBK

**Comment by pdliuw** [comment]
> 火星文是因为你没有转成GBK

那么应该怎么转换呢？

**Comment by chiuhol** [comment]
连接打印机配对失败，有解决方案吗

**Comment by thon-ju** [comment]
没有适配过，没有这么多设备，主要适配过gprinter
