### ISSUE TITLE
ios 编译出错 library not found for -lGSDK

### ISSUE THREAD

**Issue by liyangmsn** [thon-ju/bluetooth_print#4]
OTHER_LDFLAGS里已经有了-l"GSDK"

但是编译时候提示
library not found for -lGSDK

**Comment by thon-ju** [comment]
@liyangmsn 可以如下操作
1、删掉 other linker flags 中的-lGSDK
![image](https://user-images.githubusercontent.com/2316202/71306859-18fd5e00-2421-11ea-8d23-4be622d89180.png)
2、确保库引用了
![image](https://user-images.githubusercontent.com/2316202/71306861-2dd9f180-2421-11ea-861c-ec401402d37d.png)

**Comment by liyangmsn** [comment]
@thon-ju 
应该还需要把podspec里的s.vendored_libraries = '**/*.a'去掉
这行代码会往other linker flags里添加-IGSDK

**Comment by thon-ju** [comment]
@liyangmsn 理论上这样子，新功能引用的时候回自动添加GSDK.a，去掉了，新工程需要手动添加GSDK.a库，但是实际上没有起效果。你还有更好方式推荐吗？

**Comment by liyangmsn** [comment]
@thon-ju 不好意思 我查了一遍文档还是没有解决
目前所知vendored_libraries是将库引入
但是我看项目里也已经引入了 所以我感觉问题不在这里
我想问下这个GSDK是干嘛用的  没有相关文档

**Comment by thon-ju** [comment]
@liyangmsn 
这是gprinter的打印指令库，

**Comment by liyangmsn** [comment]
找到原因了  引用方法没问题
库的文件名要以lib为前缀
https://stackoverflow.com/questions/19189463/cocoapods-podspec-issue

**Comment by thon-ju** [comment]
@liyangmsn 经过测试，的确可以。非常感谢
