### ISSUE TITLE
update bluetooth_print to flutterEmbedding v2 

### ISSUE THREAD

**Issue by UnluckyY1** [thon-ju/bluetooth_print#51]
i have been using this plugin for more than 6 month now without an issue but after adding new futures to my app like backgroundtask with `workmanager` and noftications with `flutter_local_notfication` will cause 
`Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@c154952) but could not find and invoke the GeneratedPluginRegistrant.`
removing `bluetooth_print` from yaml file will make things works perfectly

```
C:\flutter\.pub-cache\hosted\pub.dartlang.org\bluetooth_print-2.0.0\android\src\main\java\com\example\bluetooth_print\BluetoothPrintPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
this plugin is the only one within the flutter community that serves my app needs (it can even be a paid task)

**Comment by thon-ju** [comment]
@UnluckyY1 can you show me your development environment configuration？

**Comment by UnluckyY1** [comment]
@thon-ju 
Flutter doctor : 
```
[√] Flutter (Channel stable, 1.22.6-0.0.pre.1, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[!] Connected device
    ! No devices available
```

**Comment by thon-ju** [comment]
@UnluckyY1 this plugin update , can you test again?
