### ISSUE TITLE
Does it use Bluetooth Low Energy?

### ISSUE THREAD

**Issue by jobypthomas** [thon-ju/bluetooth_print#55]
When using another bluetooth package (esc_pos_bluetooth) I had the issue with releasing the app in Apple AppStore. That is apple had the following feedback:

> Your app declares support for bluetooth-central and bluetooth-peripheral in the UIBackgroundModes key in your Info.plist but does not provide Bluetooth Low Energy functionality. The Bluetooth Background modes are for apps that communicate to other devices using Bluetooth Low Energy and the Core Bluetooth framework.
> 
> To resolve this issue, please revise your app to add support for Bluetooth Low Energy communication through Core Bluetooth in your app or remove the bluetooth- values from the UIBackgroundModes key.

The following background mode capabilities are what they have issue with:

	<key>UIBackgroundModes</key>
	<array>
		<string>bluetooth-central</string>
		<string>bluetooth-peripheral</string>
       </array>

Does this library uses Bluetooth Low Energy(BLE)?

**Comment by thon-ju** [comment]
yes

**Comment by alvinsear** [comment]
I faced the same problem any solution ?

**Comment by alvinsear** [comment]
> When using another bluetooth package (esc_pos_bluetooth) I had the issue with releasing the app in Apple AppStore. That is apple had the following feedback:
> 
> > Your app declares support for bluetooth-central and bluetooth-peripheral in the UIBackgroundModes key in your Info.plist but does not provide Bluetooth Low Energy functionality. The Bluetooth Background modes are for apps that communicate to other devices using Bluetooth Low Energy and the Core Bluetooth framework.
> > To resolve this issue, please revise your app to add support for Bluetooth Low Energy communication through Core Bluetooth in your app or remove the bluetooth- values from the UIBackgroundModes key.
> 
> The following background mode capabilities are what they have issue with:
> 
> ```
> <key>UIBackgroundModes</key>
> <array>
> 	<string>bluetooth-central</string>
> 	<string>bluetooth-peripheral</string>
>    </array>
> ```
> 
> Does this library uses Bluetooth Low Energy(BLE)?

I faced the same problem any solution ?
