### ISSUE TITLE
ios 这么吊，直接返回了

### ISSUE THREAD

**Issue by bxxasn** [thon-ju/bluetooth_print#68]
if ([@"state" isEqualToString:call.method]) {
    result(nil);
  } else if([@"isAvailable" isEqualToString:call.method]) {
    
    result(@(YES));
  } else if([@"isConnected" isEqualToString:call.method]) {
    
    result(@(NO));
  } else if([@"isOn" isEqualToString:call.method]) {
    result(@(YES));

**Comment by zhujiahong** [comment]
是啊 那咋判断啊
