### ISSUE TITLE
How to save _device instance for relaunch

### ISSUE THREAD

**Issue by hamzamon** [thon-ju/bluetooth_print#8]
Hello, Thank you for bluetooth_print plugin, I am interested and testing the plugin in Android and iOS, mean while I am realizing that we need to select the device on every launch of application, to avoid this, how to save _device instance for ever until disconnect the device. 

Thanks.

**Comment by hamzamon** [comment]
Resolved!, I have used shared preferance to save printer name, then search the printer and coonect on relaunch.
Thanks.

**Comment by thon-ju** [comment]
@hamzamon yes, this just right

**Comment by turkialawlqy** [comment]
> Resolved!, I have used shared preferance to save printer name, then search the printer and coonect on relaunch.
> Thanks.

Can the code be shared ?!
